#!/usr/bin/env bash
# Installs and setup haproxy
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.4
apt-get -y update
apt-get install haproxy=2.4.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                         echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 24842-web-01 44.210.108.191:80 check
   server 24842-web-02 35.174.19.217:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
